### ISSUE TITLE
G_Attractor_Mass initialization

### ISSUE THREAD

**Issue by elect86** [MauriceGit/Partikel_accelleration_on_GPU#8]
It seems `G_Attractor_Mass` initialization is missing... or am I wrong?

Because it should be null when you try to assign it to the `vec.w`

`vec.w = G_Attractor_Mass[i];`

**Comment by MauriceGit** [comment]
Yes, you are completely right.
I commented it out, because like observed, it is not properly used.
And not read at all. So it just set vec.w to Zero (constantly) for now.

Thanks!
