### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by LeifHenriksen** [MauriceGit/Partikel_accelleration_on_GPU#9]
Hi, I compiled and ran your program, it works but I get a lot of flickering (blue, red, blue, red). I would like to know if you have the same problem.

I am using Ubuntu.

Thanks in advance.

**Comment by MauriceGit** [comment]
Hi,

I'm on Mint, so Ubuntu should be fine! Does it technically work? The coloring should be dependent on delta time between frames, so shouldn't flicker (well, theoretically).

Do the particles disappear as fast as the colors change or is it just colors?

Best regards,
Maurice

**Comment by LeifHenriksen** [comment]
Hi,

The problem was my old computer not the software, sorry for the inconvenience.

Best regards,

Leif

**Comment by MauriceGit** [comment]
Hey, 
alright, that's good to hear! No inconvenience at all, thanks for reporting back so I can close the issue.
Best regards
Maurice
